name: Test

# triggers on
on: [push]

jobs:
  test:
    env:
      RAILS_ENV: test
      NODE_ENV: test
    runs-on: ubuntu-latest # runner
    steps:
      - name: Checkout repository # copies repo in runner
        uses: actions/checkout@v2 # short for https://github.com/actions/checkout
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1 # short for https://github.com/ruby/setup-ruby
        with:
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Get Yarn cache directory path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Setup cache key and directory for node_modules cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: bundle exec rspec
